# sfm algorithm configure
social_force:
  animation_factor: 5.1
  # only handle pedestrians within `people_distance`
  people_distance: 6.0
  # weights of social force model
  goal_weight: 2.0
  obstacle_weight: 80.0
  social_weight: 15
  group_gaze_weight: 3.0
  group_coh_weight: 2.0
  group_rep_weight: 1.0

# pedestrians setting
pedestrians:
  update_rate: 5
  ped_tracker:
    enable: true
    model: DROW3
    weight: ckpt_jrdb_ann_drow3_e40.pth
  ped_property:
    - name: human_0
      pose: 2.36 2.18 1 0 0 0
      velocity: 0.9
      radius: 0.4
      cycle: false
      # time_delay: 5
      ignore:
        model_1: ground_plane
        model_2: turtlebot3_waffle
      trajectory:
        goal_point_1: 2.36 2.18 1 0 0 0
        goal_point_2: 7.64 7.82 1 0 0 0
    - name: human_1
      pose: 8.21 2.72 1 0 0 0
      velocity: 0.9
      radius: 0.4
      cycle: false
      # time_delay: 5
      ignore:
        model_1: ground_plane
        model_2: turtlebot3_waffle
      trajectory:
        goal_point_1: 8.21 2.72 1 0 0 0
        goal_point_2: 1.79 7.28 1 0 0 0
    - name: human_2
      pose: 1.38 6.36 1 0 0 0
      velocity: 1.2
      radius: 0.4
      cycle: false
      # time_delay: 3
      ignore:
        model_1: ground_plane
        model_2: turtlebot3_waffle
      trajectory:
        goal_point_1: 1.38 6.36 1 0 0 0
        goal_point_2: 8.62 3.64 0 0 0
    - name: human_3
      pose: 8.41 6.77 1 0 0 0
      velocity: 1.2
      radius: 0.4
      cycle: false
      # time_delay: 3
      ignore:
        model_1: ground_plane
        model_2: turtlebot3_waffle
      trajectory:
        goal_point_1: 8.41 6.77 1 0 0 0
        goal_point_2: 1.59 3.23 1 0 0 0
    - name: human_4
      pose: 8.96 5.18 1 0 0 0
      velocity: 1.2
      radius: 0.4
      cycle: false
      # time_delay: 3
      ignore:
        model_1: ground_plane
        model_2: turtlebot3_waffle
      trajectory:
        goal_point_1: 8.96 5.18 1 0 0 0
        goal_point_3: 1.04 4.82 1 0 0 0
    - name: human_5
      pose: 7.28 1.88 1 0 0 0
      velocity: 1.2
      radius: 0.4
      cycle: false
      # time_delay: 3
      ignore:
        model_1: ground_plane
        model_2: turtlebot3_waffle
      trajectory:
        goal_point_1: 7.28 1.88 1 0 0 0
        goal_point_2: 2.72 8.12 1 0 0 0
