# sfm algorithm configure
social_force:
  animation_factor: 5.1 # default: 5.1
  people_distance: 6.0 # default: 6.0, only handle pedestrians within `people_distance`
  goal_weight: 2.0 # default: 2.0, weights of social force model
  obstacle_weight: 60.0 # default: 10.0
  social_weight: 2.1 # default: 2.1, you can also set seperately in pedestrians setting
  group_gaze_weight: 3.0
  group_coh_weight: 2.0
  group_rep_weight: 1.0

# pedestrians setting
pedestrians:
  update_rate: 5
  ped_tracker:
    enable: true
    model: DROW3
    weight: ckpt_jrdb_ann_drow3_e40.pth
  ped_property:
    - name: human_1
      pose: 6 -1 1 0 0 0
      velocity: 0.9
      radius: 0.4
      social_weight: 5.0
      time_delay: 1
      cycle: true
      ignore:
        model_1: ground_plane
        model_2: turtlebot3_waffle
      trajectory:
        goal_point_1: 6 -1 1 0 0 0
        goal_point_2: -6 1 1 0 0 0
      group:
        model_1: human_2
        model_2: human_3
    - name: human_2
      pose: 6 0 1 0 0 0
      velocity: 0.9
      radius: 0.4
      social_weight: 10.0
      time_delay: 2
      cycle: true
      ignore:
        model_1: ground_plane
        model_2: turtlebot3_waffle
      trajectory:
        goal_point_1: 6 0 1 0 0 0
        goal_point_2: -6 0 1 0 0 0
      group:
        model_1: human_1
        model_2: human_3
    - name: human_3
      pose: 6 1 1 0 0 0
      velocity: 0.9
      radius: 0.4
      social_weight: 15.0
      time_delay: 3
      cycle: true
      ignore:
        model_1: ground_plane
        model_2: turtlebot3_waffle
      trajectory:
        goal_point_1: 6 1 1 0 0 0
        goal_point_2: -6 -1 1 0 0 0
      group:
        model_1: human_1
        model_2: human_2
    - name: human_4
      pose: -6 -1 1 0 0 0
      velocity: 0.9
      radius: 0.4
      social_weight: 20.0
      time_delay: 4
      cycle: true
      ignore:
        model_1: ground_plane
        model_2: turtlebot3_waffle
      trajectory:
        goal_point_1: -6 -1 1 0 0 0
        goal_point_2: 6 1 1 0 0 0
      # group:
      #   model_1: human_5
      #   model_2: human_6
    - name: human_5
      pose: -6 0 1 0 0 0
      velocity: 0.9
      radius: 0.4
      social_weight: 12.0
      time_delay: 5
      cycle: true
      ignore:
        model_1: ground_plane
        model_2: turtlebot3_waffle
      trajectory:
        goal_point_1: -6 0 1 0 0 0
        goal_point_2: 6 0 1 0 0 0
      # group:
      #   model_1: human_4
      #   model_2: human_6
    - name: human_6
      pose: -6 1 1 0 0 0
      velocity: 0.9
      radius: 0.4
      social_weight: 18.0
      time_delay: 6
      cycle: true
      ignore:
        model_1: ground_plane
        model_2: turtlebot3_waffle
      trajectory:
        goal_point_1: -6 1 1 0 0 0
        goal_point_2: 6 -1 1 0 0 0
      # group:
      #   model_1: human_4
      #   model_2: human_5
