map: blank
world: empty
robot_config:
  robot_type: turtlebot3_waffle
  robot_x_pos: 5.0
  robot_y_pos: 1.0
  robot_z_pos: 0.0
  robot_yaw: 0.0
rviz_file: sim_env.rviz
pedestrians: ped_circle_config.yaml
# pedestrians: pedestrians_config.yaml

# obstacles: obstacles_config.yaml
